### ISSUE TITLE
convention dotfiles for config in repos

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/website#16]
- I don't like it
- why?
- prevent deletion?
- makes sense in HOME, to hide things
- but not in repository, where they are tracked
- mixed up with actual cache stuff (`.cache`)
- prevent name collision? better convention that dot?
- location? root? subfolder? not possible for git. same for other tools (editorconfig). meta.toml? config.toml?

```toml
[tool.editorconfig]
filename = "editorconfig"

[tool.pytest]
filepath = "config/pytest.ini"
```
